# Generated by Django 4.0.2 on 2022-02-16 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0009_alter_image_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='order',
            field=models.IntegerField(blank=True, default=0, verbose_name='Порядок'),
        ),
    ]
